model:
  method: structured
  name: Baseline
  kwargs:
    geo_dim: 2
    param_dim: 2
    latent_dim: 32
    out_dim: 3
data:
  dataset: structured 
  data_dir: ./data/official/npy
  plotter: structured
  