model:
  geo_dim: 2
  param_dim: 2
  latent_dim: 256
  out_dim: 3
data:
  prepare: False
  generate_from: ''
  data_dir: './data/npy'
  batch_size: 32
training:
  max_epochs: 1500
  check_val_every_n_epoch: 10
  auto_lr_find: False
  